# Chigraph main site
# Built using Jekyll

title: Chigraph
email: dev@chigraph.io
description: > # this means to ignore newlines until "baseurl:"
  A simple, flowgraph-based programming language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chigraph.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
gems:
  - jekyll-archives
  - jekyll-sitemap
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - update.sh

sass:
  sass_dir: _sass

permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
